# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:15:25+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ConvertPostRequest(BaseModel):
    hundreds_form: Optional[str] = Field(
        None,
        description='Some use مائة others use مئة , both works in Arabic. If left empty the default is مائة ',
        examples=['مائة'],
    )
    the_number: Optional[str] = Field(
        None,
        description='Put the number here. Decimal is supported by most units.',
        examples=['2519.50'],
    )
    unit: Optional[str] = Field(
        None,
        description='The counted subject, be it a currency like درهم إماراتي  or a size unit like متر مربع\nIf the unit does not appear in the text result, it may not be supported. Please contact us to add it.',
        examples=[' ريال سعودي'],
    )
